### ISSUE TITLE
Documentation Layout

### ISSUE THREAD

**Issue by paragonie-scott** [paragonie/pecl-libsodium-doc#1]
How does this sound as a basic outline?
1. Introduction
   - What is Libsodium?
   - Terms and Concepts
   - Installing Libsodium and the PHP extension
2. Quick Start Guide
   - Which tool to use, for which purpose?
3. Random data
4. Utilities and Helpers
   - `bin2hex()`/`hex2bin()`
   - `memzero()`
   - `increment()`
   - `memcmp()`
5. Basic Secret-key Cryptography
   - `crypto_secretbox()`
   - `crypto_auth()`
6. Basic Public-key Cryptography
   - `crypto_box()`
   - `crypto_sign()`
7. Hashing
   - `crypto_generichash()`
   - `crypto_shorthash()`
8. Password Hashing
   - `crypto_pwhash()` (when available)
   - `crypto_pwhash_scryptsalsa208sha256_str()`
9. Advanced
   - `crypto_aead_*()`
   - `crypto_scalarmult()`
   - `crypto_stream()`
   - `crypto_stream_xor()`
   - `crypto_box_seal()`
   - `crypto_kx()`
   - Key conversion (get publickey from secretkey, get keypair from seed, etc.)
10. Recipes
    - Put some common use-cases here (e.g. encrypted cookies, sealed logs)

**Comment by jedisct1** [comment]
Sounds really good!
