### ISSUE TITLE
Add PPA for Ubuntu 12.04 LTS

### ISSUE THREAD

**Issue by bitbeans** [paragonie/pecl-libsodium-doc#2]
Add 

https://answers.launchpad.net/~chris-lea/+archive/ubuntu/libsodium

Alternative: https://launchpad.net/~anton+/+archive/ubuntu/dnscrypt

to: https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium

**Comment by paragonie-scott** [comment]
:+1: I'll add that to my next commit (working on the utilities & helpers; I think it will make more sense for me to do the quick start piece last).
