### ISSUE TITLE
5/8 byte output lenght

### ISSUE THREAD

**Issue by MikeRow** [paragonie/pecl-libsodium-doc#22]
Hello, I need an ouput of 5 or 8 byte to generate a crypto work or validate an account

$state = sodium_crypto_generichash_init(null, 5);
$state = sodium_crypto_generichash_init(null, 8);

But I can't set less than 16. Any way to solve this?

**Comment by jedisct1** [comment]
You can output 16 bytes and truncate to 5 bytes if this is really what you need.

**Comment by MikeRow** [comment]
Ok, I'll try, to keep the output correct, should I truncate from begin or end? Apply any reverse?

**Comment by jedisct1** [comment]
Whatever. All bits have the same properties.
